name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  async_redux: ^25.4.0
  connectivity_plus: ^6.1.4
  fast_immutable_collections: ^11.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  http_client:
    path: ../http_client
  logging: ^1.3.0
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  pro_lints: ^4.0.0
