name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  async_redux: ^25.0.0
  connectivity_plus: ^6.1.3
  fast_immutable_collections: ^11.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  http_client:
    path: ../http_client
  logging: ^1.3.0
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  pro_lints: ^3.0.1

dependency_overrides:
  meta: ^1.12.0
