import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;

import '../command_runner.dart';
import '../engine/changeset.dart';
import '../version.dart';

/// Generates one agent skill per frx command, plus the router that sits over
/// them, into the repository's `.claude/skills/`.
///
/// **Why one per command.** A traced run measured the failure this replaces: an
/// agent read `frx --help`, then `README.md`'s full command map, then
/// `frx help` for eleven commands — all inside the first forty seconds — and
/// then, thirty minutes later, hand-wrote fifty-six selector getters and every
/// state field. Three documents carried the index and none of them fired at the
/// moment of writing. A skill's description is matched by the harness on every
/// step instead of being recalled, so the decision is made where it is taken.
///
/// **What is generated and what is authored.** Everything mechanical — the
/// invocation, the aliases, the flag list — comes off the `Command` objects
/// themselves, so it cannot drift from the CLI the way a hand-kept copy does
/// (this repository has already paid for that once, in the editor extension).
/// The one authored part is [_Situation.when]: the description is the trigger,
/// and it has to match how the task sounds in someone's head, not what the
/// command is called. "A value computed from state" finds `add-selector`;
/// "add-selector" only finds it if you already knew.
class SkillGen {
  /// path (relative to repo root) -> file content.
  static Map<String, String> generate() {
    final runner = FrxRunner();
    final out = <String, String>{};

    for (final cmd in runner.commands.values) {
      if (cmd.hidden) continue;
      final s = _situations[cmd.name];
      if (s == null) continue; // covered by the router instead
      out['.claude/skills/frx-${cmd.name}/SKILL.md'] = _skill(cmd, s);
    }
    out['.claude/skills/wiring-artifacts/SKILL.md'] = _router();
    out['.claude/skills/asyncredux-in-this-template/SKILL.md'] = _asyncRedux;
    out['.claude/skills/data-driven-widgets/SKILL.md'] = _dataDrivenUi;
    return out;
  }

  /// The file that records which skill directories frx wrote, and with which
  /// version.
  ///
  /// **Ownership, not a prefix.** The tree is generated whole, so a skill for a
  /// command that no longer exists has to go rather than linger as a trigger
  /// for nothing — and the prune that did that matched `frx-` and
  /// `asyncredux-`, which by then was two of the four kinds generated:
  /// `wiring-artifacts` and `data-driven-widgets` were never swept, so renaming
  /// either would have left the old one live. A prefix cannot be the rule
  /// anyway, because a project may keep skills of its own beside these, and
  /// deleting one of those is not a mistake it can recover from.
  static const manifestName = '.frx-owned';

  /// The frx these skills are generated by — what the manifest records and what
  /// `doctor` compares a project's copy against.
  static const version = frxVersion;

  /// [manifestName]'s content for what [generate] produces.
  static String manifest() => _manifestOf(directories());

  static String _manifestOf(Set<String> produced) {
    final b = StringBuffer()
      ..writeln('# Written by `frx update-skills`. Do not edit.')
      ..writeln('#')
      ..writeln('# Every directory below is frx\'s to rewrite and to remove.')
      ..writeln('# Anything in .claude/skills/ that is not listed here is')
      ..writeln('# yours, and frx will not touch it.')
      ..writeln('version: $frxVersion');
    for (final dir in (produced.toList()..sort())) {
      b.writeln(dir);
    }
    return b.toString();
  }

  /// The skill directory names [generate] produces.
  static Set<String> directories() => _directoriesOf(generate());

  static Set<String> _directoriesOf(Map<String, String> generated) => {
    for (final path in generated.keys) p.split(path)[2],
  };

  /// What the manifest under [skillsDir] says was written, and by which version.
  ///
  /// Empty when there is none — a project made before this command existed, or
  /// one whose `.claude/skills/` frx has never written. The caller decides what
  /// that means; nothing is inferred from the directory names themselves,
  /// because that is the guess this file exists to stop making.
  static ({String? version, Set<String> directories}) ownedIn(
    Directory skillsDir,
  ) {
    final file = File(p.join(skillsDir.path, manifestName));
    if (!file.existsSync()) return (version: null, directories: const {});

    String? version;
    final dirs = <String>{};
    for (final line in file.readAsLinesSync()) {
      final trimmed = line.trim();
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
      if (trimmed.startsWith('version:')) {
        version = trimmed.substring('version:'.length).trim();
        continue;
      }
      // A name, never a path. The line is joined to `.claude/skills/` and the
      // result is deleted *recursively*, so a manifest carrying `../../business/lib`
      // — hand-edited despite the banner, mangled by a merge, or written by a
      // future frx in a format this one does not know — would take a package
      // with it. Anything that is not a bare segment is not something this
      // wrote, and is ignored rather than acted on.
      if (p.basename(trimmed) != trimmed || trimmed == '.' || trimmed == '..') {
        continue;
      }
      dirs.add(trimmed);
    }
    return (version: version, directories: dirs);
  }

  /// The changes that bring `.claude/skills/` under [root] up to this frx.
  ///
  /// Built here rather than in the command because there are two callers and
  /// they must not drift: `frx update-skills` previews it, `doctor --fix`
  /// applies it. A second derivation of "what updating skills means" is the
  /// shape this repository keeps paying for.
  ///
  /// An unchanged file is left out, so a project already current plans nothing.
  /// [generated] lets a caller that already rendered the tree hand it over.
  /// `generate()` builds a `FrxRunner` — every command object and its parser —
  /// and renders every skill, and the audit calls this on every debounced save
  /// in the editor; without it this ran twice per call, and three times per
  /// `update-skills`.
  static List<Change> changesIn(
    Directory root, {
    Map<String, String>? generated,
  }) {
    final skillsDir = Directory(p.join(root.path, '.claude', 'skills'));
    generated ??= generate();
    final changes = <Change>[];

    for (final entry in generated.entries) {
      final file = File(p.join(root.path, entry.key));
      if (!file.existsSync()) {
        changes.add(WriteFile(file.path, entry.value));
        continue;
      }
      final before = file.readAsStringSync();
      if (before == entry.value) continue;
      changes.add(EditFile(file.path, before: before, after: entry.value));
    }

    // Only what the last run recorded as its own, minus what this run makes. A
    // skill the project wrote itself is not in the manifest, so it is never a
    // candidate — which is the whole reason the manifest exists.
    final produced = _directoriesOf(generated);
    final stale = ownedIn(skillsDir).directories.difference(produced).toList()
      ..sort();
    for (final dir in stale) {
      final directory = Directory(p.join(skillsDir.path, dir));
      if (directory.existsSync()) changes.add(DeleteDirectory(directory.path));
    }

    final manifestFile = File(p.join(skillsDir.path, manifestName));
    final content = _manifestOf(produced);
    if (!manifestFile.existsSync()) {
      changes.add(WriteFile(manifestFile.path, content));
    } else {
      final before = manifestFile.readAsStringSync();
      if (before != content) {
        changes.add(
          EditFile(manifestFile.path, before: before, after: content),
        );
      }
    }

    return changes;
  }

  static String _skill(Command<int> cmd, _Situation s) {
    final alias = cmd.aliases.isEmpty ? '' : ' (alias `${cmd.aliases.first}`)';
    final b = StringBuffer()
      ..writeln('---')
      ..writeln('name: frx-${cmd.name}')
      ..writeln('description: >-')
      // The description is the trigger, so it carries the situation and the
      // command name and stops there. Splicing the CLI's own one-liner in as a
      // clause reads as a conjugation bug ("which add a field…") because those
      // are imperative, and the body repeats it verbatim two lines down.
      // The prohibition stays. Anthropic's guide recommends negative triggers
      // in a description, and the 650-trial comparison has imperative-plus-
      // prohibition activating 98.6% against 62.6% for the imperative alone.
      // The opposite rule — prompt the positive — governs the body, not this.
      ..writeln(
        _wrap(
          '${s.when} ${s.wires ? 'Wired by' : 'Answered by'} '
              '`frx ${cmd.name}`$alias.'
              '${s.wires ? ' Do NOT hand-write this artifact '
                        'or edit the files it wires — run the command.' : ''}',
          '  ',
        ),
      );

    if (s.paths.isNotEmpty) {
      b.writeln('paths:');
      for (final p in s.paths) {
        b.writeln('  - "$p"');
      }
    }

    b
      ..writeln('---')
      ..writeln()
      ..writeln('# `frx ${cmd.name}`')
      ..writeln()
      ..writeln(cmd.description)
      ..writeln()
      ..writeln('```')
      ..writeln(cmd.invocation)
      ..writeln('```')
      ..writeln();

    // Context first: what the thing is comes before what to watch out for.
    if (s.context != null) {
      b.writeln(s.context!.trim());
      b.writeln();
    }

    if (s.traps.isNotEmpty) {
      b.writeln('## Before you run it');
      b.writeln();
      for (final t in s.traps) {
        b.writeln('- ${_wrap(t, '  ').trimLeft()}');
      }
      b.writeln();
    }

    b
      ..writeln('## Flags')
      ..writeln()
      ..writeln('```')
      ..writeln(cmd.argParser.usage.trimRight())
      ..writeln('```')
      ..writeln()
      ..writeln(_shared)
      ..writeln()
      ..writeln(_gates);
    return b.toString();
  }

  static String _router() {
    return '''
---
name: wiring-artifacts
description: >-
  Router for this Flutter AsyncRedux + auto_route monorepo — picks which `frx`
  command wires the artifact you are about to write, and carries the rules that
  belong to no single command. Use when several artifacts are needed at once,
  when it is unclear which command owns a change, right after hand-editing files
  of this architecture, or before deleting anything — reaching for `rm` on a file
  of this architecture is the signal.
---

# Wiring artifacts of this architecture

Every artifact this architecture has is created and wired by one `frx` command,
and each command carries its own skill — how the artifact is written here, and
what its help does not say. Those skills reach you on their own: they fire on
the situation, and the file-editing ones fire again on the file. Reading them
ahead of time is not how they work and not how they are counted.

`frx --help` lists the commands. This file carries what belongs to no single one.

Names take any casing — `myProfile`, `my_profile`, `MyProfile` and `my-profile`
all resolve to the same artifact.

## More than one artifact at once

`frx batch` takes the intents as data and wires them in **one** transaction, in
the order written. A shell loop over the same commands is the usual substitute
and is not the same thing: it has no rollback boundary, so a failure at the
fifth intent leaves the first four wired and the state half-built. Batch covers
the creation commands only — `rename` and `remove` are refused with the reason.

## The rules that belong to no single command

- **A write applies completely or not at all.** A failed write is
  indistinguishable from a write never attempted, so a zero exit means the whole
  changeset landed and you never have to parse anything to find out. Exit `64` is
  a usage error, `70` is "cannot do this here". What sits outside the
  transaction: `dart format`, the `docs/flows` refresh and `build_runner` run
  after it and roll nothing back.
- **After editing files by hand, run the audit, then the type analyzer.** The
  audit knows this architecture and the analyzer knows Dart; neither substitutes
  for the other. The way this one is lost is not skipping it but spacing it — run
  it once before starting and once when done and the whole middle went
  unmeasured, every finding surfacing where any of a hundred edits could have
  caused it.
- **The graph is a gate you close as you go.** The audit and the analyzer both
  pass on code nothing reaches: a selector no reader calls, an action no widget
  dispatches. The moment is precise — the feature compiles, and you have not
  started the next one.
- **Deletion goes through `frx remove`, not `rm`.** It knows a substate, a page,
  an action, a model or enum, a widget, a connector and a service, and it deletes
  the *set*: a service's dispatcher, a model's `.freezed.dart` and `.g.dart`,
  a substate's whole folder. That set is the whole point — `rm` takes the
  file you name and leaves the rest, and the generated halves it leaves stop the
  package compiling on a file you never wrote. What `remove` does not do is chase
  the code that used the artifact, so the audit still follows. A theme extension
  and a retrofit client have no kind yet; those two are still `rm` plus the audit.
  A **field** of a substate is `frx remove <field> --kind field --state <slice>`,
  and it is the one deletion `rm` cannot even attempt: the field is a line inside
  a file that stays, and the guard refuses the hand edit that would take it out.
  A slice made with the default kind arrives carrying `value` — this is how it
  leaves, with its `Select…` getter and its setter action.
- **Around a live `build_runner watch`, commands stand down.** They hand the
  build over rather than starting a second one. The fact is reported in the
  command's own result (`--json` carries it as `build.handedToWatch`), not by the
  audit — read it there, at the moment you act. An *orphaned* watch is the
  converse: it regenerates nothing, and the audit reports it.
- **A reducer reads through the facade and writes through nested `copyWith`.**
  `login.email`, not `state.login.email` — the getters come from the `Selectors`
  mixin, on the `Action` base and on a connector's `_Factory` alike, and the
  graph can only see the read that way. The write is `state.copyWith.login(email:
  value)`, freezed's nested form.
- **`ui` is data-driven and knows no domain.** A widget draws what it is handed;
  the connector is the seam where a domain value becomes a primitive, a formatted
  string or a `ui`-local render model. A component with its own lifecycle earns a
  file in a family folder, which is what gives it a name anything else can
  reach — inside a page it has none, and the next screen that needs it copies
  it. **How a widget is fed — the render model, where it lives, and what goes in
  its equality — is `data-driven-widgets`.** That skill fires on the situation;
  it is the one to have read before writing a widget or a `fromStore`, because a
  view-model that compares wrong does not crash, it redraws everything or shows
  a moment that has passed.

## Writing the body, not just the file

A command scaffolds the file and its wiring. How the body is written afterwards
is this architecture's own, and in several places it is the opposite of what
async_redux's documentation shows — `@freezed` rather than a hand-written
`copy()`, an `extension type` facade rather than memoised selector functions,
`extends Action` rather than `extends ReduxAction`.

Read **`asyncredux-in-this-template`** before filling in a reducer, a connector
or a state class, and whenever recalled async_redux knowledge is about to be
applied here. Each command's own skill carries the rules for its artifact.

## Project defaults

A `.frxrc` at the repo root sets the house style once — `buildRunner`, `format`,
`substateKind`, and a `placement` block that silences an audit rule by id. An
explicit flag always wins.

## Orientation

- [`README.md`](../../../README.md) — the architecture and the full command map.
- `frx --help` — the authority, and it always travels with the CLI.
- `docs/flows/` is **generated** from the sources. Regenerate it, never hand-edit
  it; the audit reports it as drift when it falls behind.
''';
  }

  /// Fold to ~76 columns so the frontmatter stays readable in a diff.
  static String _wrap(String text, String indent) {
    final words = text.split(RegExp(r'\s+')).where((w) => w.isNotEmpty);
    final lines = <String>[];
    var line = indent;
    for (final w in words) {
      if (line.length + w.length + 1 > 76 && line.trim().isNotEmpty) {
        lines.add(line.trimRight());
        line = indent;
      }
      line += '$w ';
    }
    if (line.trim().isNotEmpty) lines.add(line.trimRight());
    return lines.join('\n');
  }

  static const _shared = '''
Every writing command takes `--dry-run` (plan only), `--json` (the changeset as
data), and `--force`. A non-zero exit means none of it landed.''';

  static const _gates = '''
## After

`frx doctor`, then `dart analyze`. When the feature is finished and before the
next one starts, `frx graph` — it is the only one that names code nothing
reaches.''';
}

class _Situation {
  /// A command that writes or moves an artifact of this architecture. Its skill
  /// carries the prohibition, because hand-writing one of these writes the files
  /// and misses the wiring.
  const _Situation.wired(
    this.when, {
    this.context,
    this.paths = const [],
    this.traps = const [],
  }) : wires = true;

  /// A command that answers a question. Nothing to forbid — and, as the
  /// analyzer pointed out the moment the two were split, nothing to describe or
  /// to glob on either: [context] says what an artifact *is*, [paths] fires on
  /// the file being edited, and a command that writes no artifact has neither.
  const _Situation.read(this.when, {this.traps = const []})
    : wires = false,
      context = null,
      paths = const [];

  /// Whether the description forbids hand-writing what this command wires.
  ///
  /// **Two constructors rather than a flag, and no unnamed one, so this cannot
  /// be left undecided.** It used to be a `_writes` set of command names 620
  /// lines from the only place that read it — and both reads were inside
  /// `_skill()`, where this object is already in hand. It had already come
  /// apart: `add-package` extends `WritingCommand`, and creating a package is
  /// five changes across two directories of which four alone leave a workspace
  /// that does not resolve, yet its skill said only "Answered by".
  ///
  /// It is not `cmd is WritingCommand`: `batch` and `rename` wire artifacts
  /// without extending it, and `update-skills` extends it and writes frx's own
  /// files rather than the project's — though that one never reaches here, since
  /// a command with no situation gets no skill.
  final bool wires;

  /// The trigger. Written the way the task sounds before the command is known.
  final String when;

  /// Globs that make the skill load when those files are being worked on.
  ///
  /// The measured failure this targets: an agent read five state files and
  /// rewrote them wholesale ten minutes after reading the skill that says not
  /// to. A description cannot fix that, because the standard says an agent
  /// "only consult[s] skills for tasks that require knowledge or capabilities
  /// beyond what they can handle alone" — and writing a Dart file looks like
  /// one it can. `paths` fires on the file instead of on the intent.
  ///
  /// Only for commands that edit an artifact that already exists. A creation
  /// command has no file to match yet, and a glob would narrow it to nothing.
  final List<String> paths;

  /// What the artifact *is*, in this template's terms, with code from it.
  ///
  /// The command help says what the command writes; it cannot say how the body
  /// is written afterwards, and that is where an agent falls back on recalled
  /// async_redux knowledge — which is right about the library and wrong here in
  /// five places (freezed rather than a hand-written `copy()`, an `extension
  /// type` facade rather than memoised selector functions, `extends Action`
  /// rather than `extends ReduxAction`, `IList` rather than `List`, private
  /// `_Factory`/`_Vm` in the connector file). Raw markdown, so it can carry the
  /// fenced code that makes the shape unambiguous.
  final String? context;

  final List<String> traps;
}

/// Authored: how each job sounds in the moment, plus what its help omits.
/// `create`, `new` and `completions` are deliberately absent — they are not
/// reached for mid-task, and the router names them.
/// The async_redux context that belongs to no single command.
///
/// Not a copy of the library's documentation. What an agent already knows about
/// async_redux is mostly right and, in five places, exactly wrong here — so this
/// states the divergence and stops. Anything a command owns lives in that
/// command's skill instead.
const _asyncRedux = r'''
---
name: asyncredux-in-this-template
description: >-
  How async_redux is actually used in this monorepo, where it diverges from the
  library's own documentation, and the pieces no `frx` command owns —
  dispatching, waiting, user-facing errors, persistence and injected
  dependencies. Use before writing the body of a reducer, a connector or a state
  class, and whenever recalled async_redux knowledge is about to be applied
  here.
---

# async_redux, as this template uses it

## Five places the library's docs point the wrong way

| Stock async_redux | Here |
| --- | --- |
| an immutable class with its own `copy()` | `@freezed`, and `state.copyWith.<slice>(…)` for a nested write |
| `extends ReduxAction<AppState>` | `extends Action` — it mixes in `Selectors` and types `deps` and `env` |
| selector functions memoised with `cache1` / `cache2` | a facade of `extension type`s over `AppState`, zero-cost, nothing to memoise |
| `VmFactory` / `Vm` written however | `_Factory` / `_Vm`, private, in the connector file, `with Selectors` |
| `List` / `Map` in state | `IList` / `IMap` / `ISet` |

Everything below is the part no command scaffolds.

## Dispatching

- `dispatchSync` — a synchronous reducer. Setters from a connector use this.
- `dispatchAndWait` — returns the `ActionStatus`; await it when the next step
  depends on whether the action succeeded.
- `dispatch` — fire and forget, including `GoAction` for navigation.

Navigation is itself an action (`GoAction.push` / `replace` / `navigate` / `pop`
/ `popUntilRoot`), so it is observable and testable like any other, and
connectors never poke the router.

## Waiting

`Wait` is a field on `AppState`, owned by async_redux. An action opts in with the
`WaitingAction` mixin, which raises the barrier in `before()` and clears it in
`after()`. The reader is a selector keyed on the action type:

```dart
bool get isWaiting => _state.wait.isWaitingForType<LogInWithEmailAction>();
```

`frx add-action -k waiting` writes both. Never reduce `wait` yourself.

## Errors the user should see

Throw `UserException` from a reducer and async_redux shows it. `store.dart`
installs a `GlobalErrorObserver` that logs, wraps anything else into a
`UserException`, and gives the app a first chance to translate through a
`UserErrorWrapperHandler` returning a `LocalizedMessage` (title + message) — so a
message can be localised without `business` depending on the app's locale.

## Persistence

`AppPersistor` (`business/lib/persistor.dart`) is a `Persistor<AppState>` over
`KeyValueStorage` from `storage`. Boot goes through `createStore`: open storage,
read the persisted state, fall back to `AppState.initial()`. The app layer never
touches the storage backend. A persistor rebuilds state without dispatching,
which is why `frx graph` gives it a node of its own.

## Injected dependencies and environment

`AppDependencies` is built once by the store and reaches a reducer as `deps` on
the `Action` base; `Environment` (base URL, prod/dev) reaches it as `env`. Both
are already typed there — reading `store.dependencies` and casting is the long
way round.

## What this template does not use

Undo/redo, stream and timer actions, the provider integration, flutter_hooks,
events, `abortDispatch`, the optimistic-update mixin, and async_redux's testing
helpers — the template ships no test harness at all. If a task genuinely needs
one of these it is new ground here, not an established pattern: say so rather
than adopting it silently.
''';

/// Shared by `add-page` and `add-connector`: both scaffold the same three
/// classes, so the shape is stated once rather than twice.
const _connectorContext = r'''
## What a connector is here

Three classes in one file under `app/lib/connectors/`, two of them private. The
public one carries `@RoutePage()` and does nothing but wire the other two:

```dart
@RoutePage()
class LogInPageConnector extends StatelessWidget {
  const LogInPageConnector({super.key});

  @override
  Widget build(BuildContext context) => StoreConnector<AppState, _Vm>(
    debug: this,
    vm: () => _Factory(this),
    builder: (context, vm) => LogInPage(email: vm.email, theme: vm.theme),
  );
}
```

The factory reads the store. `with Selectors` is what lets it say `login.email`
instead of reaching into the state, and it is where a dispatch is bound to a
callback:

```dart
class _Factory extends VmFactory<AppState, LogInPageConnector, _Vm>
    with Selectors {
  _Factory(super._connector);

  @override
  _Vm fromStore() => _Vm(
    email: FieldVm(
      value: login.email,
      validator: emailValidator,
      onChanged: (v) => dispatchSync(SetEmailAction(v)),
    ),
    onPressedLogIn: () => dispatchAndWait(LogInWithEmailAction()),
    onPressedRegister: () => dispatch(GoAction.push(const RegistrationRoute())),
  );
}
```

The view-model holds what the dumb widget needs, and `equals:` names **only the
fields that carry data**:

```dart
class _Vm extends Vm {
  _Vm({required this.email, required this.onPressedLogIn})
    : super(equals: [email]);

  final FieldVm<String?> email;
  final VoidCallback onPressedLogIn;
}
```

A callback is a fresh closure every build, so listing one in `equals:` makes the
view-model unequal to itself and the connector rebuilds on every dispatch. That
is why a value and the callback that changes it travel together as `FieldVm`
(or `ChoiceVm`, when the value comes from a finite set): its `props` deliberately
omit the closures, so the value can be compared and the behaviour cannot break
the comparison.

**Which dispatch:** `dispatchSync` for a synchronous setter, `dispatchAndWait`
when the next step depends on the result, `dispatch(GoAction.push(...))` for
navigation. Connectors never touch the router directly.

This file is also the seam between the domain and the screen: `ui` depends on
neither `models` nor `business`, so an enum, a `DateTime` or a domain object
becomes a primitive, a formatted string or a `ui`-local render model **here**,
before it is handed over.
''';

const _situations = <String, _Situation>{
  'add-substate': _Situation.wired(
    'A new slice of application state — a list or table of things, a search, '
    'or a single value the app holds onto.',
    context: r'''
## What a state slice is here

The store holds one immutable `AppState`. It is never edited — a reducer returns
a new one. `AppState` is a `@freezed` class composing the slices, and every slice
has an entry in `initial()`:

```dart
@freezed
abstract class AppState with _$AppState {
  const factory AppState({
    required LoginState login,
    required ThemeState theme,
    required Wait wait,
  }) = _AppState;

  factory AppState.initial() => const AppState(
    login: LoginState(),
    theme: ThemeState(),
    wait: Wait.empty,
  );
}
```

`wait` is async_redux's own barrier registry, not a slice of this app. Leave it
alone — actions raise and clear it through the `WaitingAction` mixin.

A slice is a `@freezed` class of its own, at
`business/lib/redux/<slice>/models/<slice>_state.dart`. Every field is nullable
or carries `@Default(…)`, because the state is constructed with no arguments,
and collections are `IList` / `IMap` / `ISet` — value equality is what stops a
connector rebuilding on an identical list.

**`--kind` picks the shape**, and changing it later is a rewrite:

- `value` — one `String? value`, plus `SetValueAction`
- `search` — a `String? query` and an `IList<int> view` of results, plus
  `SetQueryAction`
- `table` — an `IMap<int, Object> table` and an `IList<int> view` over it, plus
  `Add…Action` / `Retrieve…Action`

```dart
@freezed
abstract class TodosState with _$TodosState {
  const factory TodosState({
    @Default(IMapConst<int, Object>({})) IMap<int, Object> table,
    @Default(IListConst<int>([])) IList<int> view,
  }) = _TodosState;
}
```

The slice is never read directly. The command writes its getters into the
selector facade, so a screen says `todos.view` and so does a reducer —
`_state.todos.view` appears only inside the facade itself.
''',
    traps: [
      'The kind decides the shape: `table` for a keyed collection with an '
          'ordering, `search` for a query with results, `value` for one value. '
          'Ask which before scaffolding — changing it later is a rewrite.',
      'It wires the `AppState` field *and* its `initial()` entry, the selectors '
          'facade and the change log. What dispatches its starter actions is '
          'yours.',
    ],
  ),
  'add-field': _Situation.wired(
    'A piece of data a state slice does not hold yet — the slice already '
    'exists and needs one more field on it. Also the shape of a slice you '
    'just created: each field is one of these, not a file you open and type.',
    paths: ['business/lib/redux/*/models/*_state.dart'],
    context: r'''
## What a field is here

A field belongs to a slice's `@freezed` class. Adding one is three coordinated
edits, and the command makes all three.

**1. The factory**, spliced in via AST. A field is either nullable or carries
`@Default(…)`, because the state is constructed with no arguments:

```dart
const factory TodosState({
  @Default(IMapConst<int, Object>({})) IMap<int, Object> table,
  @Default(IListConst<int>([])) IList<int> view,
  DateTime? dueAt,
}) = _TodosState;
```

A collection field is `IList` / `IMap` / `ISet`, and the import comes with it.
`List` / `Map` compare by identity, so a connector would rebuild on an identical
list.

**2. The getter on the facade**, so anything can read the field without knowing
where it sits:

```dart
/// Returns dueAt
DateTime? get dueAt => _state.todos.dueAt;
```

`--no-selector` skips it. Rarely what you want: a field a connector cannot read
is half-wired, and it is this getter that makes the read visible to `frx graph`.

**3. A setter action**, with `--action` — positional constructor, `final` field,
and freezed's nested `copyWith`:

```dart
class SetDueAtAction extends Action {
  SetDueAtAction(this.dueAt);

  final DateTime? dueAt;

  @override
  AppState reduce() => state.copyWith.todos(dueAt: dueAt);
}
```

That `state.copyWith.<slice>(<field>: …)` form is how every write to a slice is
spelled — not `state.copyWith(todos: state.todos.copyWith(…))`.
''',
    traps: [
      'The field is spliced into the `@freezed` factory via AST. A '
          'non-nullable type **requires** `--default`, because a state is '
          'constructed with no arguments.',
      'It also writes the `Select…` getter, unless `--no-selector`. A field a '
          'connector cannot read is half-wired — which is why hand-writing the '
          'field means hand-writing the facade too, and usually forgetting it.',
      '`IList` / `IMap` / `ISet` types auto-import '
          '`fast_immutable_collections`. `--action` scaffolds the '
          '`Set<Field>Action` setter and never clobbers an existing one.',
      'Taking one out is `frx remove <field> --kind field --state <slice>` — '
          'the inverse of this command, and the only way: the state file '
          'refuses a hand edit in either direction. It takes the factory '
          'parameter, the facade getter and the `Set<Field>Action` together, '
          'and prunes an import nothing else needs.',
    ],
  ),
  'add-selector': _Situation.wired(
    'A value computed from state rather than stored in it — a count, a '
    'filtered list, a derived flag; anything a screen reads that the state '
    'does not hold directly.',
    paths: ['business/lib/redux/selectors.dart'],
    context: r'''
## What a selector is here

Not a function, and nothing to memoise. async_redux's own documentation teaches
selector functions cached with `cache1` / `cache2`; this template has none of
that. A selector is a getter on an `extension type` over `AppState`, so reading
one is a field access, and all of them live in a single file,
`business/lib/redux/selectors.dart`:

```dart
extension type SelectLogin(AppState _state) {
  /// Returns waiting value
  bool get isWaiting => _state.wait.isWaitingForType<LogInWithEmailAction>();

  /// Returns email value
  String? get email => _state.login.email;
}
```

The facade is the `Selectors` mixin, and mixing it in is the only way in:

- a reducer, because `Action` mixes it in — `login.email`
- a connector's `_Factory`, for the same reason

There is no root type and no `state.select` hop. There were both, plus a
`Select` extension type carrying the same getter list as the mixin, and nothing
in the template ever called them — so adding a slice cost two parallel lists,
one of which was unreachable.

A value that spans slices belongs to `SelectComposites`, on the facade itself —
not inside one of the slices:

```dart
extension SelectComposites on Selectors {
  bool get canEnterApp => session.isAvailable && !login.isWaiting;
}
```

That works because `Selectors` has every slice in scope. A `SelectX` does not
reach its siblings, and in the whole template not one of them tried to.

`doctor` reports a selector declared anywhere but the facade
(`selector-outside-facade`), so the file is the convention, not a habit.
''',
    traps: [
      '`--expr` is the getter body and defaults to reading the state field of '
          'the same name; `--type` tightens the return type from `Object?`. No '
          'codegen — selectors are hand code.',
      'A selector nothing reads is reported by the graph as a fact, not a '
          'defect: in a template it can be API for whoever builds on it.',
    ],
  ),
  'add-action': _Situation.wired(
    'Something that changes state — a reducer, a mutation, an async operation '
    'a screen dispatches.',
    context: r'''
## What an action is here

An action is a class with a `reduce()` method. You dispatch it; the store calls
`reduce()` and replaces the state with what it returns. Returning `null` means
"no state change" — the action still ran, and observers still see it.

Actions extend **`Action`**, not `ReduxAction<AppState>`. The base lives in
`business/lib/redux/common/action.dart` and is what gives a reducer its three
tools:

```dart
abstract class Action extends ReduxAction<AppState> with Selectors {
  AppDependencies get deps => store.dependencies! as AppDependencies;
  Environment get env => store.environment! as Environment;
}
```

- `Selectors` — the selector facade, so state is read as `login.email`
- `deps` — injected services
- `env` — base URL, prod/dev

**Synchronous.** Parameters arrive through the constructor as `final` fields;
the write is freezed's nested `copyWith`:

```dart
class SetEmailAction extends Action {
  SetEmailAction(this.value);

  final String? value;

  @override
  AppState reduce() => state.copyWith.login(email: value);
}
```

**Asynchronous.** `Future<AppState?> reduce() async`, and every path must
`await`. Reads go through the facade — `login.email`, never `state.login.email`:

```dart
class LogInWithEmailAction extends Action with WaitingAction {
  @override
  Future<AppState> reduce() async {
    await _request(email: login.email!, password: login.password!);

    return state.copyWith(login: const LoginState());
  }
}
```

`with WaitingAction` raises a wait barrier for the duration — `before()` puts it
up, `after()` takes it down — and a screen asks about it through a selector,
`isWaiting => _state.wait.isWaitingForType<LogInWithEmailAction>()`.

**How it is dispatched**, from a connector's `_Factory`: `dispatchSync` for a
synchronous setter, `dispatchAndWait` when the next step depends on the result,
plain `dispatch` for fire-and-forget.
''',
    traps: [
      'The suffix is optional and idempotent: `ArchiveTask` and `ArchiveTaskAction` scaffold the '
          'same artifact. Do not strip it yourself, and do not add it — pass '
          'the name as you have it. `frx remove` reads the same rule, so '
          'whichever spelling created it removes it.',
      'Mixins conflict, and the conflict is a **compile error**: async_redux '
          'makes groups mutually exclusive by colliding on a private member. '
          'Ask `frx list-mixins` which exclude which and let the scaffolder '
          'write the `with` clause — it refuses a bad pair up front.',
      '`-k waiting` also adds the substate\'s `isWaiting` getter, on the same '
          'ground as a field\'s getter: a waiting action a page cannot ask '
          'about is half-wired.',
    ],
  ),
  'add-page': _Situation.wired(
    'A new screen and the route that reaches it.',
    context: _connectorContext,
    traps: [
      'The suffix is optional and idempotent: `Home` and `HomePage` scaffold the '
          'same artifact. Do not strip it yourself, and do not add it — pass '
          'the name as you have it. `frx remove` reads the same rule, so '
          'whichever spelling created it removes it.',
      'It wires the page, its `@RoutePage()` connector, the `AutoRoute` entry '
          'and auth-area membership (`--public`). Navigation **to** it is a '
          'separate decision — that is `add-nav`.',
      '`--param name:type` becomes both a `/:name` path segment and a '
          'constructor field.',
    ],
  ),
  'add-tabs': _Situation.wired(
    'A tabbed shell — several screens living under one tab bar, as a nested '
    'route.',
    traps: [
      'The suffix is optional and idempotent: `Main` and `MainPage` scaffold the '
          'same artifact. Do not strip it yourself, and do not add it — pass '
          'the name as you have it. `frx remove` reads the same rule, so '
          'whichever spelling created it removes it.',
    ],
  ),
  'add-nav': _Situation.wired(
    'Getting from one screen to another — a tap that opens another page.',
    paths: ['app/lib/connectors/*.dart', 'app/lib/navigation/*.dart'],
    traps: [
      'Five edits across two packages, four of which alone leave code that '
          'does not compile. `--kind` picks the `GoAction` factory: `push`, '
          '`replace` or `navigate`.',
    ],
  ),
  'add-widget': _Situation.wired(
    'A reusable piece of UI in the `ui` package — an input, a button, a tile, '
    'a container.',
    context: r'''
## What a widget is here — `ui` is data-driven

A widget draws what it is handed and decides nothing. It does not fetch, derive,
look up or branch on the domain. Its inputs are data and callbacks: primitives,
a `ui`-local render model, `FieldVm` / `ChoiceVm`.

This is a boundary, not a preference. `ui` depends on neither `models` nor
`business`, so a domain type cannot even be named in this package — the
conversion happens in the connector, the one place that sees both sides.

```dart
class InputFormField extends StatelessWidget {
  const InputFormField({required this.vm, this.labelText, super.key});

  final FieldVm<String?> vm;
  final String? labelText;

  @override
  Widget build(BuildContext context) => TextFormField(
    initialValue: vm.value,
    validator: vm.validator,
    onChanged: vm.onChanged,
    decoration: InputDecoration(labelText: labelText),
  );
}
```

`FieldVm` is what makes that possible: the value, its `onChanged`, an optional
validator and a server-side error arrive as one object, and its `props` omit the
closures so the view-model above can still compare equal between builds.

**Text: chrome is looked up, content arrives resolved.** A widget's own fixed
label may come from `S.current`, because `ui` does depend on `localization`.
Anything that depends on the domain or the data — an option's label, a formatted
date, a pluralised count — arrives as a finished `String`, resolved in the
connector where the locale and the domain both live. `ChoiceItemVm.label` puts it
in one line: *label is data, not design*.
''',
    traps: [
      'It writes the file; what the widget is *handed* is the part that goes '
          'wrong. `data-driven-widgets` carries it — the render model, where it '
          'lives, and what belongs in its equality.',
      '`--dir` is required and open-ended: a name that does not exist creates '
          'the folder. Ask `frx list-widget-dirs` which already hold widgets '
          'instead of inventing a home.',
      '`-k` picks what it takes in: `field` takes a `FieldVm`, `choice` a '
          '`ChoiceVm`, `action` is a labelled button, `view` draws a render '
          'model, `container` wraps children.',
      '**The kind adds a suffix to the name**, and the file is named after the '
          'resulting class: `-k field Pin` writes `PinFormField` in '
          '`pin_form_field.dart`, `-k action Submit` writes `SubmitButton`. '
          '`view` and `container` add none. Adding it yourself is harmless — '
          'the suffix is idempotent — but a name that reads right in the '
          'command can come out different on disk, so check the plan before '
          '`--apply` if the spelling matters.',
      'None of the kinds wraps `SegmentedControl`. A control over a set the '
          'design fixes is `-k view` plus a `FieldVm` — `ThemeSwitcher` and '
          '`LanguageSwitcher` are the precedent, and `data-driven-widgets` '
          'says why it is not a `ChoiceVm`.',
      'A component with its own lifecycle earns a file in a family folder — '
          'never a private `StatefulWidget` inside a page. Hidden there it has '
          'no name anything else can reach, so the next screen that needs it '
          'copies it instead. There is not one in the package.',
    ],
  ),
  'add-connector': _Situation.wired(
    'Connecting a dumb widget to the store — the `StoreConnector` that builds '
    'its view-model.',
    paths: ['app/lib/connectors/*.dart'],
    context: _connectorContext,
    traps: [
      'Converting a domain value here means **naming its type here**, and `app` '
          'does not depend on `models` out of the box — no connector in the '
          'template converts one. Add `models` to `app/pubspec.yaml` and run '
          '`flutter pub get`; `frx add-package` creates a workspace member and '
          'does not draw a dependency edge between two that exist.',
      'The suffix is optional and idempotent: `Toolbar` and `ToolbarConnector` scaffold the '
          'same artifact. Do not strip it yourself, and do not add it — pass '
          'the name as you have it. `frx remove` reads the same rule, so '
          'whichever spelling created it removes it.',
    ],
  ),
  'add-model': _Situation.wired(
    'A data shape the app passes around — a freezed model, or a sealed union '
    'when the value is one of several cases.',
    traps: [
      'It writes `factory Task({required int id})` and stops. **The fields are '
          'yours to add**, by hand, in the factory it wrote — `add-field` is '
          'for a substate\'s state class and refuses a model. Then run '
          '`build_runner` in `models`, or nothing compiles: a freezed model is '
          'half generated.',
      '`-c <case>` twice or more makes it a sealed union with one factory per '
          'case. Three answers as three cases beat a nullable field with a '
          'flag beside it.',
    ],
  ),
  'add-enum': _Situation.wired(
    'A fixed set of values — a status, a priority, a mode.',
  ),
  'add-service': _Situation.wired(
    'A service and the Redux dispatcher that lets it reach the store.',
    traps: [
      'The suffix is optional and idempotent: `Sync` and `SyncService` scaffold the same artifact. Do not strip it yourself, and do not add it — pass the name as you have it. `frx remove` reads the same rule, so whichever spelling created it removes it.',
    ],
  ),
  'add-package': _Situation.wired(
    'A whole workspace member is missing — `add-model` or `add-retrofit` '
    'refused because the package it writes into is not in this project.',
    paths: ['pubspec.yaml'],
    context: r'''
## Which packages are optional

`models` and `http_client` are optional, and a project may have been created
without them — `frx create --without models,http_client` is what leaves them
out. `app`, `business`, `ui` and `localization` are not — the app does not
compile without them, so there is nothing to add.

| kind | holds | written into by |
| --- | --- | --- |
| `models` | freezed models and JSON converters shared between packages | `add-model` |
| `http_client` | Dio + Retrofit clients and interceptors | `add-retrofit` |
| `storage` | key-value persistence behind `BaseKeyValueStorage` | nothing — `AppPersistor` uses it |

## What it writes

Five files and two kinds of edit, applied together or not at all: the package's
`pubspec.yaml` (with `resolution: workspace`, the line that makes it a member),
`analysis_options.yaml`, `build.yaml` where a builder runs, `.gitignore`,
`lib/.gitkeep` — one entry spliced into the root pubspec's `workspace:` list,
and the path dependency spliced into each package that declares it (`business`
for all three, and `http_client` for `models`).

## After it runs

**`flutter pub get` from the workspace root, before anything else.** A new
member changes what pub resolves, and until it has run the package is a
directory the analyzer cannot see. That is why this command runs no codegen of
its own — build_runner needs the resolution it just invalidated.
''',
    traps: [
      'It declares the dependency in the packages the template declares it in, '
          'and nowhere else. A **different** package that wants to import '
          '`package:models/…` still needs the entry in its own `pubspec.yaml`.',
      'Asking for a package that is already a member is not an error: it '
          'writes nothing and says so.',
    ],
  ),
  'add-retrofit': _Situation.wired(
    'An HTTP API client — endpoints against a base URL.',
  ),
  'add-theme-extension': _Situation.wired(
    'Theme values the design needs — colours, sizes, spacing read off the '
    'theme.',
  ),
  'batch': _Situation.wired(
    'Several artifacts at once — a whole feature\'s worth of state, screens '
    'and actions, wired together.',
    traps: [
      'One rollback boundary where eight invocations are eight boundaries: a '
          'failure at the fifth intent leaves nothing of the first four.',
      'Intents apply **in the order written** and fail loudly — `add-action` '
          'refuses a substate that is not there — so a prerequisite comes '
          'first. Nothing is reordered for you, on purpose.',
      'Creation commands only. `rename` and `remove` are refused, and an '
          'intent carrying `--dry-run`, `--json`, `--build-runner` or '
          '`--format` is refused too: those decide whether the batch writes.',
    ],
  ),
  'remove': _Situation.wired(
    'Deleting any artifact — a state slice, a field on one, a screen, an '
    'action, a model, a widget, a connector, a service — with everything that '
    'points at it.',
    traps: [
      'Previews by default; `--apply` is what touches disk.',
      'The kind is auto-detected; pass `--kind` only when the name matches '
          'more than one, and `--state` when an action name is used under more '
          'than one substate.',
      'A **field** is the exception: it is never auto-detected, so it is '
          '`--kind field` every time, plus `--state` unless one slice alone '
          'has a field of that name. It takes the factory parameter, the '
          '`Select…` getter and the `Set<Field>Action` together — and it is '
          'the only way out of a field, since the state file refuses a hand '
          'edit.',
      'Removing a field is **refused** while something still reads it — a '
          'computed getter on the state class, a hand-written selector over '
          'it. Rewrite those first: a selector body is yours to edit, so that '
          'is the end you start from. Actions that merely assign the field are '
          'named in the plan and left alone; fix them after.',
      'Reach for it instead of `rm`, which deletes the file you name and '
          'leaves the rest of the set: a service\'s dispatcher, a model\'s '
          '`.freezed.dart` and `.g.dart` — '
          'and those two stop the package compiling once their source is gone.',
      'It deletes the artifact and unwires what registered it. It does not '
          'chase the code that used it: what still dispatches a deleted action '
          'or imports a deleted model is yours to fix, so run the audit after.',
    ],
  ),
  'rename': _Situation.wired(
    'Renaming a state slice or a screen — files, classes and every wiring '
    'reference.',
    traps: [
      'Previews by default; `--apply` is what touches disk. Identifiers move '
          'off the parse tree, so a name inside a persistence key survives '
          'untouched.',
    ],
  ),
  'doctor': _Situation.read(
    'Checking the project is still consistent — after hand edits, after a '
    'deletion, or before calling something done.',
    traps: [
      'It finds wiring drift, ungenerated code and misplaced declarations — '
          'what the Dart analyzer cannot know. Run both.',
      '`--fix` repairs what is safe to repair: runs codegen, removes an orphan '
          'substate folder that holds nothing. Placement findings never '
          'auto-fix — a deliberately placed file is the false positive being '
          'accepted.',
    ],
  ),
  'graph': _Situation.read(
    'What reaches what — who can change this slice, what breaks if it is '
    'touched, and which selectors or actions nothing reaches at all.',
    traps: [
      '`--focus` takes a node id, a symbol or a bare name; `-d inbound` '
          'answers "what breaks if I touch this" and is unbounded by default.',
      'The `unresolved` section matters as much as the edges: a missing edge '
          'and a relation that does not exist look identical, so the gaps are '
          'named rather than dropped.',
      '**"No dispatcher found" is not always dead code.** The walk starts at '
          'connectors, actions and service dispatchers, so an action '
          'dispatched from anywhere else — the boot in `run_env.dart` being '
          'the one the template itself needs — is reported as reached by '
          'nobody. Check where it is dispatched before deleting it; a '
          'substate\'s `Retrieve…Action` is the expected case.',
    ],
  ),
  'flow': _Situation.read(
    'What actually happens when the user taps something, how the screens '
    'connect, or refreshing the generated flow docs.',
    traps: [
      '`--md` writes `docs/flows/`; `--check` verifies it is current and exits '
          '1 when not. Never hand-edit that folder.',
    ],
  ),
  'which': _Situation.read(
    'What artifact a class, route or field belongs to — and the canonical name '
    'to hand `rename`.',
  ),
  'list-substates': _Situation.read(
    'What state slices exist and are composed into `AppState`.',
  ),
  'list-routes': _Situation.read('What routes the router registers.'),
  'list-widget-dirs': _Situation.read(
    'Where widgets already live, before inventing a folder for a new one.',
  ),
  'list-mixins': _Situation.read(
    'Which action mixins imply what, and which exclude which — before passing '
    'a second `--mixin`.',
  ),
  'watch': _Situation.read(
    'Running codegen continuously while working, instead of after each write.',
  ),
};

/// The rule every widget in `ui` is written under, and the one no command can
/// scaffold: what a widget is handed, and who turns state into it.
///
/// Authored rather than derived, like [_asyncRedux]. What makes it a skill and
/// not a paragraph in the router is when it has to fire — at the moment someone
/// is about to write a widget or a `fromStore`, which is before any `frx`
/// command runs and often instead of one.
const _dataDrivenUi = r'''
---
name: data-driven-widgets
description: >-
  How a widget is built and fed in this monorepo — composed from the package's
  parts, handed a view-model rather than state, compared on what the user can
  see, and written in Dart's dot shorthand. Use before writing or changing any
  widget in `ui`, any `_Vm` / `fromStore` in a connector, or a list of anything;
  when deciding where a widget belongs or whether to make one private; and
  whenever a widget is about to be handed a domain object, a `Store`, or a
  `BuildContext` lookup instead of data. Do NOT write a widget from recalled
  Flutter habits without it.
---

# Widgets are handed data, and nothing else

```
AppState  ──_Factory.fromStore()──>  _Vm  ──builder──>  dumb widget
```

**The state does not cross the second arrow.** The connector reads the store and
produces finished values; the widget draws them. A widget that takes a `Task`, a
`Store`, an `AppState`, or reaches for one through `context` has moved the seam,
and every rule below stops holding at once.

The whole chain, in three fragments:

```dart
// ui/lib/<family>/task_tile.dart — the widget and its render model,
// together. `frx list-widget-dirs` says which families exist.
final class TaskTileVm extends Equatable {
  const TaskTileVm({required this.title, required this.due, this.onTap});

  final String title;
  final String due;              // already formatted — see "Text", below
  final VoidCallback? onTap;     // null when the row does not react

  @override
  List<Object?> get props => [title, due, onTap != null];
}

final class TaskTile extends StatelessWidget {
  const TaskTile({required this.vm, super.key});

  final TaskTileVm vm;

  @override
  Widget build(BuildContext context) => AppCard(
    child: InkWell(
      onTap: vm.onTap,
      child: Row(
        crossAxisAlignment: .start,
        children: [Text(vm.title), Text(vm.due)],
      ),
    ),
  );
}
```

```dart
// app/lib/connectors/tasks_page_connector.dart — the seam.
class _Factory extends VmFactory<AppState, TasksPageConnector, _Vm>
    with Selectors {
  _Factory(super._connector);

  @override
  _Vm fromStore() => _Vm(
    tiles: [
      for (final task in tasks.visible)
        TaskTileVm(
          title: task.name,
          due: S.current.dueOn(task.dueAt),
          onTap: task.isOpen ? () => dispatch(OpenTaskAction(task.id)) : null,
        ),
    ],
  );
}

class _Vm extends Vm {
  _Vm({required this.tiles}) : super(equals: [tiles]);

  final List<TaskTileVm> tiles;
}
```

```dart
// ui/lib/pages/tasks_page.dart — it takes render models, and decides nothing.
final List<TaskTileVm> tiles;
…
itemBuilder: (_, index) => TaskTile(vm: tiles[index]),
```

The domain `Task` appears once, inside `fromStore`, and never leaves `app`.

## Where each piece lives

| Piece | Package | Why there |
| --- | --- | --- |
| `TaskTile` — the widget | `ui` | it draws; it knows no domain |
| `TaskTileVm` — its render model | `ui`, **beside the widget**, public | it is the widget's own input shape |
| `_Vm` / `_Factory` — the screen's model | `app`, in the connector file, private | it is that screen's, and nothing else's |
| `Task` — the domain | `models` | `ui` never sees it |

A render model is `ui`-local and public, so a connector in `app` can build one;
a screen's `_Vm` is private, so nothing can reach into it.

## A widget is a part, and parts compose

`ui/lib/` is a folder per kind of part, and that taxonomy is the rule made
physical. **A widget that fits none of them is a sign the package is missing a
primitive**, not a sign to write a bigger widget.

**Ask which folders exist — do not take a list from here.** `frx
list-widget-dirs` answers it, and the answer moves: it reports only folders that
already hold a widget, so a folder emptied by a deletion stops being offered the
moment it stops being a home. A list written into this file was wrong within a
day of being written.

Build the new thing out of what is there. Three of the five archetypes
`frx add-widget` scaffolds do nothing else:

| `-k` | wraps |
| --- | --- |
| `field` | `InputFormField` |
| `choice` | `ChoiceFormField` |
| `action` | `Button` |
| `container` | whatever it is given — it takes a `child` |
| `view` | draws a render model, composed from the parts above |

A screen is the last composition, not the first: a page is a `Scaffold`, a list,
and a tile. It holds no layout the tile could have owned.

**The test for "is this a part": could another screen ask for it by name?** If
yes, it is a file in a family folder, whatever it looks like today.

### Which folder

The folder names what the widget **is**, and for three archetypes the CLI
already knows which one and offers it first:

| `-k` | goes in |
| --- | --- |
| `field`, `choice` | `inputs/` |
| `action` | `buttons/` |
| `container` | `containers/` |
| `view` | **no fixed home — decide** |

`view` has none on purpose: a card, a tile, a row and a header are all views,
and there is no answer that fits all of them. The card in this package lives in
`containers/app_card.dart`, so "cards go in `cards/`" is not a rule here. Run
`frx list-widget-dirs` and place the widget with the family it belongs to.

**Ask before inventing.** `--dir` is open-ended — a name that does not exist
creates the folder, in `lower_snake_case` — so the failure is not being refused,
it is quietly starting a second folder beside an established one and splitting a
family in two. Run `frx list-widget-dirs` first; create a folder only when the
widget is genuinely a new kind of part.

The folders that are not widget homes are refused outright: `theme`, `models`,
`generated`, `l10n`, `pages`.

## Private widgets are parts of one widget, not hidden components

A private widget is right when it is **its owner's own piece**, named for the
role it plays inside it, in the same file. The package has exactly two, and both
are that: `_Segment` in `buttons/segmented_control.dart` is one segment of a
segmented control; `_Content` in `containers/auth_from_container.dart` is the
heading-and-form column of that container. Neither means anything elsewhere.

It is wrong when it is something another screen would want. `ui/lib/pages/`
contains **no** private widget class, and that is not an accident: hidden in a
page, a component has no name anything else can reach, so the next screen that
needs it copies it — and then there are two, drifting.

Reach for a private class to keep one widget's `build` readable. Do not reach
for it to avoid deciding where a component belongs — that decision is
`frx add-widget <name> --dir <folder>`, and `frx list-widget-dirs` says which
folders already hold widgets.

## A value plus an `onChanged` is a `FieldVm`, not a new pair

`ui/lib/models/value_changed.dart` holds the shared input models, and a widget
that takes a value and reports changes takes one of them rather than declaring
`value` and `onChanged` side by side:

| The widget | takes |
| --- | --- |
| edits one value | `FieldVm<T>` — `value`, `onChanged`, `validator?`, `error?`, `enabled` |
| picks from a set **that is data** | `ChoiceVm<T>` — the same, plus `items` |
| picks from a set **fixed by design** | `FieldVm<T>` for the value, and its own list of options |

That last row is the line worth getting right, and `ChoiceVm`'s own doc draws
it: *use it when the set is data (loaded, localized, user-specific); when the
set is fixed by design, the widget declares it instead*. `SegmentedControl` is
the worked example — `FieldVm<T> vm` for the value and the callback,
`List<Segment<T>> segments` for the two or three options the design fixes.

Taking the pair loose costs three things at once: the `error` and `enabled`
states every input here already has, the equality that is already right
(`onChanged` and `validator` are behaviour, not display — they are out of
`props` on purpose), and the shape `frx add-widget -k field` scaffolds, which is
what every other input in the package looks like.

`ChoiceItemVm` carries a `label`, already resolved. `ui` does not localise an
option — see "Text", below.

## Equality is the part that goes wrong

A view-model that compares wrong does not crash. It redraws the screen on every
dispatch in the app, or leaves a region showing a moment that has passed — and
both read as "Flutter being slow" rather than as a bug in a list.

**Compare what the user can see. Leave out what they cannot.**

- **A value** — text, a flag, an id, a list of render models — goes in.
- **An optional callback goes in as `onTap != null`**, because whether a row
  reacts is visible. Never the callback itself: `fromStore` builds a fresh
  closure every time, so a model holding one is unequal to itself on every
  rebuild.
- **A callback that is always present is left out entirely.** `FieldVm` in
  `ui/lib/models/value_changed.dart` says why in a comment: `onChanged` and
  `validator` are *behaviour, not data*, so its props are `[value, error,
  enabled]`.

The screen's `_Vm` follows the same rule through `super(equals: [...])`: the
list of render models is compared, the callbacks are not. An empty `equals`
where there was something to compare rebuilds on every dispatch; a missing
member leaves the screen stale.

`frx doctor` reports a **value** field left out of equality
(`view-model-equality`). It never reports a callback — the audit catches the
omission, not the excess.

## Three strategies for a callback in a list

| Strategy | Shape | Use when |
| --- | --- | --- |
| **In the model, optional** | `onTap` on the Vm, `onTap != null` in props | tappability varies per row |
| **Out of the model** | `onTap` a widget parameter, rows keyed by `Vm.id` | every row means the same thing — one closure instead of N, and `const` models. What `frx add-widget -k view` scaffolds |
| **Not a callback** | the row carries an id, the composer dispatches | a row is a link, not a button |

The middle one is the default and the cheapest. Reach for the first when the
rows genuinely differ.

## Dot shorthand, wherever the type is known

Dart infers the type of a `.` expression from its context, and this package is
written that way throughout:

```dart
border: .all(color: context.colors.borderStrong),   // BorderSide.all
scrollDirection: .horizontal,                       // Axis.horizontal
mainAxisSize: .min,                                 // MainAxisSize.min
crossAxisAlignment: .start,                         // CrossAxisAlignment.start
alignment: .center,                                 // Alignment.center
fit: .cover,                                        // BoxFit.cover
value: .dark,                                       // ThemeMode.dark
```

Argument positions and typed fields have a context type, so the prefix is noise.
**Repeating it is the thing to fix, not a style preference** — `theme_switcher.dart`
writes `value: .dark` for one of this app's own enums, not only for Flutter's.

**Where it does not work**, and long form is correct: a declaration with no
context type to infer from.

```dart
static const _textPadding = EdgeInsets.symmetric(horizontal: 8);  // no type here
```

That is why `theme/radii.dart` and `theme/spacing.dart` are full of
`BorderRadius.all(...)` and `EdgeInsets.all(...)` — they are the declarations.

**And a token beats a literal, shorthand or not.** `radii.dart` exists so that
`BorderRadius.circular` is not written at every call site, so the best form is
`borderRadius: Radii.card`, not `.circular(8)`. Same for `Insets.md` over
`.all(16)`. Reach for the shorthand when there is no token for the value; reach
for the token first.

## Text: chrome is looked up, content arrives resolved

A widget's own fixed label may come from `S.current` — a page titles its own
`AppBar` that way. Anything depending on the domain or the data — an item's
title, a formatted date, a pluralised count — arrives as a finished `String`,
resolved in the connector where the locale and the domain both live.
`ChoiceItemVm.label` states it in one line: **label is data, not design**.

## Before you write one

- A widget with no `vm` is fine; a widget with a domain type in its constructor
  is the seam in the wrong place.
- `frx add-widget -k view <name> --dir <folder>` scaffolds the pair — render
  model and widget — with the equality already right. Reach for it rather than
  hand-writing the shape from this file.
- Composed from the package's parts, not from `Container` and `Padding` — and if
  there is no part for it, the part is what is missing.
- Building the model inside the widget, or in a `builder:`, is the failure this
  exists to prevent. It compiles, it draws, and it rebuilds on everything.
''';
