import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;

import '../command_runner.dart';
import '../engine/changeset.dart';
import '../version.dart';
import '../workspace/frx_workspace.dart';
import 'asyncredux_in_this_template.dart';
import 'command_skill.dart';
import 'data_driven_widgets.dart';
import 'situation.dart';
import 'situations.dart';
import 'wiring_artifacts.dart';

/// Generates one agent skill per frx command, plus the router that sits over
/// them, into the repository's `.claude/skills/`.
///
/// **Why one per command.** A traced run measured the failure this replaces: an
/// agent read `frx --help`, then `README.md`'s full command map, then
/// `frx help` for eleven commands — all inside the first forty seconds — and
/// then, thirty minutes later, hand-wrote fifty-six selector getters and every
/// state field. Three documents carried the index and none of them fired at the
/// moment of writing. A skill's description is matched by the harness on every
/// step instead of being recalled, so the decision is made where it is taken.
///
/// **What is generated and what is authored.** Everything mechanical — the
/// invocation, the aliases, the flag list — comes off the `Command` objects
/// themselves, so it cannot drift from the CLI the way a hand-kept copy does
/// (this repository has already paid for that once, in the editor extension).
/// The one authored part is [Situation.when]: the description is the trigger,
/// and it has to match how the task sounds in someone's head, not what the
/// command is called. "A value computed from state" finds `add-selector`;
/// "add-selector" only finds it if you already knew.
class SkillGen {
  Map<String, String>? _generated;

  /// path (relative to repo root) -> file content, rendered once per instance.
  ///
  /// Rendering builds a `FrxRunner` — every command object and its parser —
  /// and writes every skill. The audit runs on every debounced save in the
  /// editor and asks three questions of the same tree, so the answer is held
  /// here rather than re-derived per question.
  Map<String, String> generate() => _generated ??= _render();

  static Map<String, String> _render() => {
    for (final (cmd, s) in _commandsWithSkills())
      _pathOf('frx-${cmd.name}'): renderCommandSkill(cmd, s),
    for (final entry in _authored.entries) _pathOf(entry.key): entry.value,
  };

  /// The skills no command derives, by directory name, in the order they
  /// follow the command skills in the tree.
  static const _authored = <String, String>{
    'wiring-artifacts': wiringArtifactsSkill,
    'asyncredux-in-this-template': asyncReduxSkill,
    'data-driven-widgets': dataDrivenWidgetsSkill,
  };

  /// Every visible command that has a situation, paired with it. A command
  /// without one is covered by the router instead.
  static Iterable<(Command<int>, Situation)> _commandsWithSkills() sync* {
    for (final cmd in FrxRunner().visibleCommands) {
      if (situations[cmd.name] case final s?) {
        yield (cmd, s);
      }
    }
  }

  static String _pathOf(String directory) =>
      '.claude/skills/$directory/SKILL.md';

  /// The file that records which skill directories frx wrote, and with which
  /// version.
  ///
  /// **Ownership, not a prefix.** The tree is generated whole, so a skill for a
  /// command that no longer exists has to go rather than linger as a trigger
  /// for nothing — and the prune that did that matched `frx-` and
  /// `asyncredux-`, which by then was two of the four kinds generated:
  /// `wiring-artifacts` and `data-driven-widgets` were never swept, so renaming
  /// either would have left the old one live. A prefix cannot be the rule
  /// anyway, because a project may keep skills of its own beside these, and
  /// deleting one of those is not a mistake it can recover from.
  static const manifestName = '.frx-owned';

  /// The frx these skills are generated by — what the manifest records and what
  /// `doctor` compares a project's copy against.
  static const String version = frxVersion;

  /// [manifestName]'s content for what [generate] produces.
  String manifest() => _manifestOf(directories());

  /// Every file a fresh `.claude/skills/` holds — the skills and the manifest
  /// that records them — by path relative to the project root.
  ///
  /// What `frx create` writes into a new project: nothing there to sync
  /// against or to delete, so none of [changesIn]'s reading applies.
  Map<String, String> files() => {
    ...generate(),
    p.posix.join('.claude', 'skills', manifestName): manifest(),
  };

  static String _manifestOf(Set<String> produced) {
    final b = StringBuffer()
      ..writeln('# Written by `frx update-skills`. Do not edit.')
      ..writeln('#')
      ..writeln("# Every directory below is frx's to rewrite and to remove.")
      ..writeln('# Anything in .claude/skills/ that is not listed here is')
      ..writeln('# yours, and frx will not touch it.')
      ..writeln('version: $frxVersion');
    for (final dir in (produced.toList()..sort())) {
      b.writeln(dir);
    }
    return b.toString();
  }

  /// The skill directory names [generate] produces.
  Set<String> directories() => _directoriesOf(generate());

  static Set<String> _directoriesOf(Map<String, String> generated) => {
    for (final path in generated.keys) p.split(path)[2],
  };

  /// What the manifest under [skillsDir] says was written, and by which
  /// version.
  ///
  /// Empty when there is none — a project made before this command existed, or
  /// one whose `.claude/skills/` frx has never written. The caller decides what
  /// that means; nothing is inferred from the directory names themselves,
  /// because that is the guess this file exists to stop making.
  static ({String? version, Set<String> directories}) ownedIn(
    Directory skillsDir,
  ) {
    final file = File(p.join(skillsDir.path, manifestName));
    if (!file.existsSync()) {
      return (version: null, directories: const {});
    }

    String? version;
    final dirs = <String>{};
    for (final line in file.readAsLinesSync()) {
      final trimmed = line.trim();
      if (trimmed.isEmpty || trimmed.startsWith('#')) {
        continue;
      }

      if (trimmed.startsWith('version:')) {
        version = trimmed.substring('version:'.length).trim();
        continue;
      }
      // A name, never a path. The line is joined to `.claude/skills/` and the
      // result is deleted *recursively*, so a manifest carrying
      // `../../business/lib` — hand-edited despite the banner, mangled by a
      // merge, or written by a future frx in a format this one does not know —
      // would take a package with it. Anything that is not a bare segment is
      // not something this wrote, and is ignored rather than acted on.
      if (p.basename(trimmed) != trimmed || trimmed == '.' || trimmed == '..') {
        continue;
      }
      dirs.add(trimmed);
    }

    return (version: version, directories: dirs);
  }

  /// The changes that bring `.claude/skills/` under [repo] up to this frx.
  ///
  /// Built here rather than in the command because there are two callers and
  /// they must not drift: `frx update-skills` previews it, `doctor --fix`
  /// applies it. A second derivation of "what updating skills means" is the
  /// shape this repository keeps paying for.
  ///
  /// An unchanged file is left out, so a project already current plans nothing.
  List<Change> changesIn(FrxWorkspace repo) {
    final skillsDir = repo.claudeSkills;
    final generated = generate();
    final changes = <Change>[
      for (final entry in generated.entries)
        ?_sync(File(p.join(repo.root.path, entry.key)), entry.value),
    ];

    // Only what the last run recorded as its own, minus what this run makes. A
    // skill the project wrote itself is not in the manifest, so it is never a
    // candidate — which is the whole reason the manifest exists.
    final produced = _directoriesOf(generated);
    final stale = ownedIn(skillsDir).directories.difference(produced).toList()
      ..sort();
    for (final dir in stale) {
      final directory = Directory(p.join(skillsDir.path, dir));
      if (directory.existsSync()) {
        changes.add(DeleteDirectory(directory.path));
      }
    }

    final manifest = _sync(
      File(p.join(skillsDir.path, manifestName)),
      _manifestOf(produced),
    );
    if (manifest != null) {
      changes.add(manifest);
    }

    return changes;
  }

  /// The write that makes [file] say [content] — none when it already does.
  static Change? _sync(File file, String content) {
    if (!file.existsSync()) {
      return WriteFile(file.path, content);
    }
    final before = file.readAsStringSync();
    if (before == content) {
      return null;
    }
    return EditFile(file.path, before: before, after: content);
  }
}
