import 'dart:io';

import 'package:path/path.dart' as p;

import '../workspace/frx_workspace.dart';
import 'flow_model.dart';
import 'mermaid.dart';
import 'route_map.dart';

/// What is wrong with one exported doc.
enum DocDriftKind {
  /// The page has no doc yet.
  missing,

  /// The doc on disk no longer matches what the source says.
  stale,

  /// A generated doc whose page is gone.
  orphan,
}

/// One out-of-date file under `docs/flows/`.
class DocDrift {
  const DocDrift(this.kind, this.path, this.relative);

  final DocDriftKind kind;

  /// Absolute path (present on disk for [DocDriftKind.stale] / `orphan`).
  final String path;

  /// Repo-relative path, for messages.
  final String relative;

  String get message => switch (kind) {
    DocDriftKind.missing => '$relative is missing',
    DocDriftKind.stale => '$relative is out of date',
    DocDriftKind.orphan => '$relative describes a page that no longer exists',
  };
}

/// Exports the flow diagrams to `docs/flows/` as markdown, and tells you when
/// what is on disk no longer matches the code.
///
/// The point of the export is documentation that cannot rot: the files are a
/// pure function of the sources, so `check()` — wired into `frx doctor` and
/// runnable in CI — fails the moment a connector changes without the docs being
/// regenerated. The whole directory is owned by frx: every file it writes is
/// stamped with [marker], and only stamped files are ever deleted.
class FlowDocs {
  FlowDocs(this.workspace);

  final FrxWorkspace workspace;

  /// Stamped into every generated file. Also the ownership test: a hand-written
  /// note dropped into `docs/flows/` has no marker, so it is left alone.
  static const marker =
      '<!-- generated by `frx flow --md` — do not edit, re-run it -->';

  /// Where the export lives. Its existence is what opts a repo in: `frx doctor`
  /// only checks freshness once this directory is there.
  Directory get dir => Directory(p.join(workspace.root.path, 'docs', 'flows'));

  bool get enabled => dir.existsSync();

  /// The files that *should* exist, by name, with their full content.
  Map<String, String> render([RouteMap? map]) {
    final routeMap = map ?? RouteMapReader(workspace).read();
    return {
      'README.md': _index(routeMap),
      for (final node in routeMap.pages)
        if (routeMap.flows[node.page] != null)
          '${node.page}.md': _page(node, routeMap.flows[node.page]!),
    };
  }

  /// How `docs/flows/` differs from what the sources say, in report order:
  /// missing, then stale, then orphaned. Empty when the export is in sync (or
  /// was never created).
  List<DocDrift> check([RouteMap? map]) {
    if (!enabled) return const [];
    final expected = render(map);
    final drift = <DocDrift>[];

    for (final entry in expected.entries) {
      final file = File(p.join(dir.path, entry.key));
      if (!file.existsSync()) {
        drift.add(DocDrift(DocDriftKind.missing, file.path, _rel(file.path)));
      } else if (file.readAsStringSync() != entry.value) {
        drift.add(DocDrift(DocDriftKind.stale, file.path, _rel(file.path)));
      }
    }

    for (final file in _ownedFiles()) {
      if (expected.containsKey(p.basename(file.path))) continue;
      drift.add(DocDrift(DocDriftKind.orphan, file.path, _rel(file.path)));
    }

    return drift;
  }

  /// Writes the export, creating `docs/flows/` if needed and deleting the docs
  /// of pages that are gone. Returns what changed — unchanged files are not
  /// rewritten, so a no-op run leaves every mtime alone.
  List<DocDrift> write([RouteMap? map]) {
    final expected = render(map);
    dir.createSync(recursive: true);

    final changed = <DocDrift>[];
    for (final entry in expected.entries) {
      final file = File(p.join(dir.path, entry.key));
      final exists = file.existsSync();
      if (exists && file.readAsStringSync() == entry.value) continue;
      file.writeAsStringSync(entry.value);
      changed.add(
        DocDrift(
          exists ? DocDriftKind.stale : DocDriftKind.missing,
          file.path,
          _rel(file.path),
        ),
      );
    }

    for (final file in _ownedFiles()) {
      if (expected.containsKey(p.basename(file.path))) continue;
      changed.add(DocDrift(DocDriftKind.orphan, file.path, _rel(file.path)));
      file.deleteSync();
    }

    return changed;
  }

  /// The `.md` files in `docs/flows/` that frx generated — i.e. that carry
  /// [marker]. Anything else in there belongs to the user.
  Iterable<File> _ownedFiles() sync* {
    if (!dir.existsSync()) return;
    for (final entity in dir.listSync()) {
      if (entity is! File || !entity.path.endsWith('.md')) continue;
      if (entity.readAsStringSync().contains(marker)) yield entity;
    }
  }

  // --- rendering --------------------------------------------------------------

  String _index(RouteMap map) {
    final b = StringBuffer()
      ..writeln(marker)
      ..writeln()
      ..writeln('# App flows')
      ..writeln()
      ..writeln(
        'Every screen the router registers, and every hop between them — read '
        'out of the connectors by `frx flow`.',
      )
      ..writeln();

    if (map.isEmpty) {
      b.writeln('_No routes registered yet._');
      return b.toString();
    }

    b
      ..writeln('```mermaid')
      ..writeln(renderRouteMap(map))
      ..writeln('```')
      ..writeln()
      ..writeln(
        'Solid arrow: `push`. Dashed: `pop` (drawn back to the only screen '
        'that pushes it, when there is exactly one). Thick: a hop that '
        'replaces the stack. `⚡` marks navigation dispatched from a reducer '
        'rather than the view-model. A dashed border means nothing pushes that '
        'screen — you arrive by path, deep link or a guard redirect.',
      )
      ..writeln()
      ..writeln('| Screen | Path | Logged out | Use cases | Flow |')
      ..writeln('| --- | --- | --- | --- | --- |');

    for (final n in map.pages) {
      final flow = map.flows[n.page] == null
          ? '—'
          : '[${n.page}](${n.page}.md)';
      b.writeln(
        '| `${n.pageClass}`${n.initial ? ' _(initial)_' : ''} '
        '| `${n.path ?? '—'}` '
        '| ${n.public ? 'yes' : 'no'} '
        '| ${n.useCases} '
        '| $flow |',
      );
    }

    return b.toString();
  }

  String _page(PageNode node, PageFlow flow) {
    final b = StringBuffer()
      ..writeln(marker)
      ..writeln()
      ..writeln('# ${node.pageClass}')
      ..writeln()
      ..writeln('`${_rel(node.connectorFile ?? '')}`')
      ..writeln();

    if (flow.isEmpty) {
      // The same distinction the CLI draws, in the artifact that outlives the
      // terminal. "Exposes no dispatching callbacks" is a claim about the code;
      // when the file does dispatch and none of it could be followed, the claim
      // is false, and this is the copy that gets committed, read later by
      // somebody who was not here, and gated on by `frx doctor`.
      if (flow.untraced.isEmpty) {
        b
          ..writeln(
            '_${flow.connectorClass} exposes no dispatching callbacks yet._',
          )
          ..writeln()
          ..writeln('[← all flows](README.md)');
        return b.toString();
      }
      b
        ..writeln(
          '_No view-model callback could be followed here, and these files '
          'dispatch anyway — so this page has interactions that are **not '
          'drawn**:_',
        )
        ..writeln();
      for (final gap in flow.untraced) {
        b.writeln('- `${gap.connectorClass}` — ${gap.calls}');
      }
      b
        ..writeln()
        ..writeln(
          '_A dispatch is followed from a `_Vm(...)` argument through the '
          'functions the file declares. One held in a field, or reached any '
          'other way, is outside that._',
        )
        ..writeln()
        ..writeln('[← all flows](README.md)');
      return b.toString();
    }

    b
      ..writeln('```mermaid')
      ..writeln(renderSequence(flow))
      ..writeln('```')
      ..writeln()
      ..writeln('| Interaction | Dispatches | Writes |')
      ..writeln('| --- | --- | --- |');

    for (final useCase in flow.useCases) {
      final targets = <String>[];
      final writes = <String>{};
      for (final step in useCase.steps) {
        targets.add('`${step.target}`${step.condition == null ? '' : ' ?'}');
        final w = flow.actions[step.target]?.writesLabel;
        if (w != null) writes.add('`$w`');
      }
      b.writeln(
        '| `${useCase.qualifiedLabel}` '
        '| ${targets.join(', ')} '
        '| ${writes.isEmpty ? '—' : writes.join(', ')} |',
      );
    }

    b
      ..writeln()
      ..writeln('`?` marks a dispatch that only runs under a condition.')
      ..writeln()
      ..writeln('[← all flows](README.md)');
    return b.toString();
  }

  /// Repo-relative, with forward slashes — the export must read the same on
  /// every machine, or `check()` would report drift after a clone.
  String _rel(String absolute) => absolute.isEmpty
      ? ''
      : p.split(p.relative(absolute, from: workspace.root.path)).join('/');
}
