@startuml "modules"
!theme vibrant

package "App" {
    [Connectors]
    [Navigation]
    Connectors ..> Business: use
    Connectors ..> UI: use
    App .left.> Localization: use
}

package "UI" {
    UI ..> Localization: use
    [Pages]
    [Buttons]
    [Inputs]
    [OtherUIElements]
}

package "Localization" {
    [en]
    [uk]
}

package "HTTPClient" {
    [AuthAPIService]
    [OtherAPIServices]
    HTTPClient ..> Models: use
}

package "Storage" {
    [HiveKeyValueStorage]
}

package "Models" {
    [User]
    [Session]
}

package "Business" {
    [Redux]
    [Services]
    Redux ..> Storage: use
    Redux .right.> HTTPClient: use
    Redux .right.> Models: use
}

@enduml
