@startuml "modules"
!theme vibrant

package "App" {
    [Connectors]
    Connectors ..> Business: use
    Connectors ..> UI: use
    App ..> Localization: use
}

package "UI" {
    UI ..> Localization: use
    [Pages]
    [OtherUIElements]
}

package "Localization" {
    [En]
    [OtherLangugages]
}

package "ApiDAO" {
    [AuthAPIService]
    [OtherAPIService]
}

package "Storage" {
    [KeyValueStorage]
}

package "Business" {
    [Redux]
    Redux ..> Storage: use
    Redux ..> ApiDAO: use
}

@enduml
