// spell: disable
@startuml "modules"
!theme vibrant

package "App" {
    [Connectors]
    [Navigation]
}

package "UI" {
    [Pages]
    [Widgets]
}

package "Localization" {
    [En]
    [Uk]
}

package "HTTPClient" {
    [API] <<Retrofit>>
    [Interseptors] <<request/response>>
}

package "Storage" {
    [Settings]
    [Session]
}

package "Models" {
    [User]
    [Product]
}

package "Business" {
    [Redux] <<state management>>
    [Services] <<core logic>>
}

App .down.> UI
App .down.> Business
App .left.> Localization
UI .left.> Localization
HTTPClient ..> Models
Business ..> HTTPClient
Business ..> Storage
Business ..> Models

@enduml
