name: models
description: The models package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  fast_immutable_collections: ^11.0.4
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  pro_lints: ^5.0.0
