name: models
description: The models package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  fast_immutable_collections: ^11.0.3
  freezed_annotation: ^3.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  pro_lints: ^3.0.1
